# Type definitions for Adopter::Converters::BaseConverter
module Adopter
  module Converters
    class BaseConverter
      RAIDER_BASE_CLASSES: Array[String]

      def convert_page: (String content, untyped _page_info) -> String
      def convert_test: (String content, untyped _test_info) -> String

      private

      def ensure_frozen_string_literal: (String content) -> String
      def update_base_class: (String content, String target_base) -> String
      def raider_compatible_base?: (String base_class) -> bool
      def update_require_paths: (String content, String target_automation) -> String
      def update_page_requires: (String content) -> String
      def update_helper_requires: (String content, String target_automation) -> String
      def remove_driver_arg: (String content) -> String
      def swap_driver_arg: (String content, String target_arg) -> String
      def driver_arg_for: (String target_automation) -> String?
    end
  end
end
