detectors:
  IrresponsibleModule:
    enabled: false

  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 10

exclude_paths:
  - 'lib/desktop/components/*.rb'
  - 'lib/desktop/screens/*.rb'
