detectors:
  Attribute:
    exclude:
      - InstallationScreen
      - RunnerScreen

  DuplicateMethodCall:
    exclude:
      - InstallationScreen

  InstanceVariableAssumption:
    exclude:
      - InstallationScreen

  IrresponsibleModule:
    enabled: false

  TooManyInstanceVariables:
    exclude:
      - InstallationScreen

  TooManyStatements:
    enabled: true
    exclude:
      - initialize
      - InstallationScreen
    max_statements: 10

