detectors:
  IrresponsibleModule:
    enabled: false

  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 10

exclude_paths:
  - 'lib/commands/open_ai_commands.rb'
