# Type definitions for main RubyRaider entry point
module RubyRaider
  class Raider < Thor
    def current_version: () -> String

    def new: (String project_name) -> void
    def version: () -> void

    private

    def merge_flags: (Hash[Symbol, untyped] params) -> void
  end
end
