# Type definitions for Plugin
module RubyRaider
  module Plugin
    def self?.add_plugin: (String plugin_name) -> void
    def self?.delete_plugin: (String plugin_name) -> String?
    def self?.installed_plugins: () -> Array[String]
    def self?.installed?: (String plugin_name) -> bool
    def self?.available?: (String plugin_name) -> bool
    def self?.camelize: (String str) -> String
    def self?.plugins: () -> Array[String]

    private

    def self?.add_plugin_to_gemfile: (String plugin_name) -> void
    def self?.remove_plugin_from_gemfile: (String plugin_name) -> void
    def self?.last_plugin?: () -> bool
    def self?.read_gemfile: () -> Array[String]
    def self?.comment_present?: () -> bool
    def self?.plugin_present?: (String plugin_name) -> bool
    def self?.remove_plugins_and_comments: (String plugin_name) -> Array[String]
    def self?.update_gemfile: (Array[String] output_lines) -> void
    def self?.gemfile_guard: () -> untyped
  end
end
