source 'https://rubygems.org'

gem 'activesupport'
gem 'allure-rspec'
gem 'allure-ruby-commons'
gem 'eyes_selenium', '~> 4.6', '>= 4.6.1'
gem 'eyes_universal', '~> 3.3', '>= 3.3.1'
gem 'rake'
gem 'reek'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'ruby_raider', '~> 0.8.0', path: "/Users/nsokol01/Documents/GitHub/ruby_raider"
gem 'selenium-webdriver'
