name: Integration tests

on: [pull_request]

jobs:
  build:
    name: Integration pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: infrastructure/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install gems
        run: bundle install

      - name: Build and run integration tests
        run: rake integration
