name: BrowserStack Test
on: [ pull_request ]

jobs:
  ubuntu-job:
    name: BrowserStack Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME
      - name: BrowserStackLocal Setup
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start


      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
        with:
          ruby-version: head

      - name: Install user input tool
        run: sudo apt-get install -y xdotool

      - name: Install Ruby Raider
        run: gem install ruby_raider

      - name: Create Raider framework
        run: raider new 'rspec_selenium'

      - name: Select Raider framework through the menu
        run: |
         xdotool key Down
         sleep 1
         xdotool key Return
         sleep 1
         xdotool key Down
         sleep 1
         xdotool key Return
         sleep 1
         xdotool key Down
         sleep 1
         xdotool key Return
         sleep 1
         xdotool key Down
         sleep 1
         xdotool key Return
         sleep 1

      - name: Run Raider tests
        run: cd rspec_selenium | rspec spec/

      - name: BrowserStackLocal Stop
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop