name: Rubocop

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
        with:
          ruby-version: head

      - name: Check out code
        uses: actions/checkout@v4

      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rspec:gemfile
          reporter: github-pr-review # Default is github-pr-check
          fail_on_error: true
