name: Watir Test on Ubuntu
on: [ pull_request ]

jobs:
  build:
    name: Watir based frameworks pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install gems
        run: bundle install

      - name: Build and run system tests
        run: rspec spec/system/watir_spec.rb
